<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>AudioDeviceLib.Test</RootNamespace>
    <AssemblyName>AudioDeviceLib.Test</AssemblyName>
    <SupportedOSPlatform>windows</SupportedOSPlatform>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Library\AudioDeviceLib.csproj" />
  </ItemGroup>

</Project>
